name: Sync Server Release to Main Repo

on:
  push:
    paths:
      - 'release-server.md'
    branches:
      - main

jobs:
  notify-main-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: techiro/release-test
          event-type: server-release-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'