name: サーバーリリース同期ワークフロー

on:
  repository_dispatch:
    types: [server-release-updated]
  workflow_dispatch:
    inputs:
      branch_name:
        description: '更新用ブランチ名'
        default: 'chore-update-proto'
        required: true

jobs:
  sync-server-release:
    runs-on: ubuntu-latest
    steps:
      # 1. 認証と初期設定
      - name: GitHub App トークンの生成
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: techiro
          repositories: release-test,release-test-server

      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          repository: techiro/release-test
          path: source
          token: ${{ steps.generate-token.outputs.token }}

      - name: ブランチ名の設定
        id: set-branch-name
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "BRANCH_NAME=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=chore-update-proto" >> $GITHUB_ENV
          fi
          echo "Using branch name: ${{ env.BRANCH_NAME }}"

      # 2. 古いブランチとプルリクエストの整理
      - name: 既存のプルリクエストのクローズ
        run: |
          PR_NUMBERS=$(curl -s -H "Authorization: token ${{ steps.generate-token.outputs.token }}" \
            "https://api.github.com/repos/techiro/release-test/pulls?state=open" | \
            jq -r ".[] | select(.head.ref == \"${{ env.BRANCH_NAME }}\") | .number")
          
          if [ -n "$PR_NUMBERS" ]; then
            echo "Found existing PRs: $PR_NUMBERS"
            for PR_NUMBER in $PR_NUMBERS; do
              echo "Closing PR #$PR_NUMBER"
              curl -X PATCH -H "Authorization: token ${{ steps.generate-token.outputs.token }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -d '{"state":"closed", "body":"自動的にクローズされました。新しいPRが作成されます。"}' \
                "https://api.github.com/repos/techiro/release-test/pulls/$PR_NUMBER"
            done
          else
            echo "No existing PRs found for branch ${{ env.BRANCH_NAME }}"
          fi
        continue-on-error: true

      - name: 既存のブランチの削除
        run: |
          BRANCH_EXISTS=$(curl -s -H "Authorization: token ${{ steps.generate-token.outputs.token }}" \
            "https://api.github.com/repos/techiro/release-test/branches/${{ env.BRANCH_NAME }}" -o /dev/null -w "%{http_code}")
          
          if [ "$BRANCH_EXISTS" == "200" ]; then
            echo "Branch ${{ env.BRANCH_NAME }} exists, deleting it"
            curl -X DELETE -H "Authorization: token ${{ steps.generate-token.outputs.token }}" \
              "https://api.github.com/repos/techiro/release-test/git/refs/heads/${{ env.BRANCH_NAME }}"
            echo "Branch deleted"
          else
            echo "Branch ${{ env.BRANCH_NAME }} does not exist or could not be accessed"
          fi
        continue-on-error: true

      # 3. サーバーリポジトリの操作
      - name: サーバーリポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          repository: techiro/release-test-server
          path: server
          token: ${{ steps.generate-token.outputs.token }}

      # 4. 生成コードの反映と整備
      - name: サーバーリリース情報の同期
        run: |
          cd source
          
          # 新しいブランチを作成
          git checkout -b ${{ env.BRANCH_NAME }}
          
          # サーバーリポジトリからrelease-server.mdをコピー
          cp ../server/release-server.md ./release-server.md
          
          # 変更があるか確認
          if [[ -n "$(git status --porcelain)" ]]; then
            # Gitの設定
            git config user.name "GitHub Actions Bot"
            git config user.email "actions@github.com"
            
            # 変更をコミット
            git add release-server.md
            git commit -m "サーバーリリース情報を更新"
            
            # 変更をプッシュ
            git push origin ${{ env.BRANCH_NAME }}
            
            echo "CHANGES_MADE=true" >> $GITHUB_ENV
            echo "Changes detected and committed"
          else
            echo "CHANGES_MADE=false" >> $GITHUB_ENV
            echo "No changes detected"
          fi

      # 5. プルリクエストの作成
      - name: プルリクエストの作成
        if: env.CHANGES_MADE == 'true'
        run: |
          PR_RESPONSE=$(curl -X POST -H "Authorization: token ${{ steps.generate-token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "title": "サーバーリリース情報を更新",
              "body": "このPRは、techiro/release-test-serverリポジトリからのサーバーリリース情報を更新します。\n\ntechiro/release-test-serverの変更によってトリガーされました。",
              "head": "${{ env.BRANCH_NAME }}",
              "base": "main",
              "draft": false
            }' \
            "https://api.github.com/repos/techiro/release-test/pulls")
          
          echo "PR creation response: $PR_RESPONSE"
          PR_URL=$(echo "$PR_RESPONSE" | jq -r '.html_url')
          
          if [ -n "$PR_URL" ] && [ "$PR_URL" != "null" ]; then
            echo "Pull request created: $PR_URL"
          else
            echo "Failed to create pull request"
            echo "$PR_RESPONSE"
            exit 1
          fi