name: Execute Repository Dispatch

on:
  push:
    paths:
      - 'release-server.md'
    branches:
      - main
  workflow_dispatch:
    inputs:
      update_note:
        description: '更新内容のメモ'
        required: false
        default: 'Updated'
        type: string
      add_date:
        description: '更新日を追加'
        required: false
        default: true
        type: boolean
      add_time:
        description: '更新時刻を追加'
        required: false
        default: true
        type: boolean

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  notify-main-repo:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        if: github.event_name == 'workflow_dispatch'

      - name: ファイルを更新
        if: github.event_name == 'workflow_dispatch'
        run: |
          # ファイル末尾に更新情報を追加
          echo "" >> release-server.md
          echo "## ${{ github.event.inputs.update_note || 'Updated' }}" >> release-server.md

          if [ "${{ github.event.inputs.add_date }}" = "true" ]; then
            echo "- 更新日: $(date +%Y年%m月%d日)" >> release-server.md
          fi

          if [ "${{ github.event.inputs.add_time }}" = "true" ]; then
            echo "- 更新時刻: $(TZ=Asia/Tokyo date +%H:%M:%S)" >> release-server.md
          fi

          # 変更をコミット
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add release-server.md
          git commit -m "手動トリガーによる更新"
          git push

      - name: 最新コミットSHAを取得
        id: get_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: repository_dispatchイベントをトリガー
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: techiro/release-test
          event-type: server-release-updated
          client-payload: |
            {"repository": "${{github.repository}}","ref": "${{ github.ref }}", "sha": "${{ steps.get_sha.outputs.sha }}", "message": "${{ github.event.inputs.update_note }}"}

      - name: repository_dispatchイベントをトリガー(server)
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: techiro/release-test-server
          event-type: server-release-updated
          client-payload: |
            {"repository": "${{github.repository}}","ref": "${{ github.ref }}", "sha": "${{ steps.get_sha.outputs.sha }}", "message": "${{ github.event.inputs.update_note }}"}
