name: dispatch event

on:
  repository_dispatch:
    types: [server-release-updated]
  workflow_dispatch:
    inputs:
      branch_name:
        description: '更新用ブランチ名'
        default: 'chore-update-server-release'
        required: true


jobs:
  handle-dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print received payload
        run: |
          echo "Ref: ${{ github.event.client_payload.ref }}"
          echo "SHA: ${{ github.event.client_payload.sha }}"
